spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/jme-deploymentlog-db-local"
    username: deploymentlog
    password: secret

jeap:
  deploymentlog:
    documentation:
      root-url: https://confluence.example.com/pages/viewpage.action?pageId=
    documentation-generator:
      confluence:
        url: "https://confluence.example.com"
        space-key: "MYSPACE"
        root-page-id: 123456789
        username: ""
        password: ""
        mock-confluence-client: true
        deployment-history-max-show: 5
      config:
        remedy-change-link-root-url: "https://remedy.example.com/smartit/app/change/displayid/"
      scheduled:
        cron: "0 0/5 * * * *"
    jira:
      app-id: 123456789
      url: https://jira.example.com
      username: ""
      password: ""
      mock-jira-client: true
