---
services:
  # Database
  jme-deploymentlog-db-local:
    image: postgres:18.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=deploymentlog
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=jme-deploymentlog-db-local
